<?php

namespace App\Helper;

class Constant {

    const CODE_SUCCESS = 200;
    const CODE_FAIL = 11;
    const CODE_PENDING = 99;
    const CODE_BAOKIM_ERROR = 101;
    const CODE_REQUEST_ID_AND_REQUEST_TIME_INVALID = 102;
    const CODE_SIGNATURE_INVALID = 103;
    const CODE_TOKEN_INVALID = 104;
    const CODE_PARTNER_CODE_DOES_NOT_EXIST = 110;
    const CODE_PARTNER_CODE_HAS_BEEN_DELETED = 111;
    const CODE_PARTNER_CODE_DOES_NOT_ACTIVE = 112;
    const CODE_OPERATION_IS_REQUIRED = 113;
    const CODE_OPERATION_INVALID = 114;
    const CODE_BANK_NO_IS_REQUIRED = 115;
    const CODE_BANK_NO_INVALID = 116;
    const CODE_ACC_NO_LENGTH_CHARACTER_INVALID = 117;
    const CODE_ACC_NO_INVALID = 118;
    const CODE_ACC_NO_SYSTEM_NOT_FOUND = 119;
    const CODE_ACC_TYPE_INVALID = 120;
    const CODE_REFERENCE_ID_IS_REQUIRED = 121;
    const CODE_REFERENCE_ID_INVALID = 122;
    const CODE_REFERENCE_ID_DOES_NOT_EXIST = 123;
    const CODE_REQUEST_AMOUNT_IS_REQUIRED = 124;
    const CODE_REQUEST_AMOUNT_INVALID = 125;
    const CODE_ERROR_PROCESSING_FROM_BANK_AND_BAOKIM = 126;
    const CODE_BANK_SYSTEM_IS_OFFLINE = 127;
    const CODE_BANK_SYSTEM_ERROR = 128;
    const CODE_NOT_ENOUGH_BALANCE = 129;
    const CODE_ACC_NAME_NOT_MATCHING = 131;
    const CODE_APP_ID_INVALID = 132;
    const CODE_CONTRACT_INVALID = 133;
    const CODE_MEMO_INVALID = 213;

}
